# Generated by Django 4.2.7 on 2024-06-30 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_recharges', models.CharField(choices=[('Mobile Recharge', 'Mobile Recharge'), ('DTH Recharge', 'DTH Recharge'), ('Insurance Payment', 'Insurance Payment')], max_length=20)),
                ('mode_of_payments', models.CharField(choices=[('UPI', 'Unified Payments Interface'), ('IB', 'Internet Banking'), ('CP', 'Card Payment')], max_length=3)),
                ('company', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.service')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.serviceuser')),
            ],
        ),
    ]
